2022/05/05 22:17:55 [error] 470#470: *5 connect() to unix:///home/rezayogaswara/python_projects/django-deploy.sock failed (111: Connection refused) while connecting to upstream, client: 139.195.129.52, server: django-deploy.rezayogaswara.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/rezayogaswara/python_projects/django-deploy.sock:", host: "django-deploy.rezayogaswara.com"
2022/05/05 22:37:22 [error] 474#474: *6 connect() to unix:///home/rezayogaswara/python_projects/django-deploy.sock failed (111: Connection refused) while connecting to upstream, client: 139.195.129.52, server: django-deploy.rezayogaswara.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/rezayogaswara/python_projects/django-deploy.sock:", host: "django-deploy.rezayogaswara.com"
2022/05/06 09:11:55 [crit] 7367#7367: *85 connect() to unix:///home/rezayogaswara/python_projects/django-deploy.sock failed (2: No such file or directory) while connecting to upstream, client: 139.195.129.52, server: django-deploy.rezayogaswara.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/rezayogaswara/python_projects/django-deploy.sock:", host: "django-deploy.rezayogaswara.com"
2022/05/06 09:11:58 [crit] 7367#7367: *85 connect() to unix:///home/rezayogaswara/python_projects/django-deploy.sock failed (2: No such file or directory) while connecting to upstream, client: 139.195.129.52, server: django-deploy.rezayogaswara.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/rezayogaswara/python_projects/django-deploy.sock:", host: "django-deploy.rezayogaswara.com"
2022/05/06 09:11:58 [crit] 7367#7367: *85 connect() to unix:///home/rezayogaswara/python_projects/django-deploy.sock failed (2: No such file or directory) while connecting to upstream, client: 139.195.129.52, server: django-deploy.rezayogaswara.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/rezayogaswara/python_projects/django-deploy.sock:", host: "django-deploy.rezayogaswara.com"
2022/05/06 09:11:59 [crit] 7367#7367: *85 connect() to unix:///home/rezayogaswara/python_projects/django-deploy.sock failed (2: No such file or directory) while connecting to upstream, client: 139.195.129.52, server: django-deploy.rezayogaswara.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/rezayogaswara/python_projects/django-deploy.sock:", host: "django-deploy.rezayogaswara.com"
2022/05/06 09:12:00 [crit] 7367#7367: *85 connect() to unix:///home/rezayogaswara/python_projects/django-deploy.sock failed (2: No such file or directory) while connecting to upstream, client: 139.195.129.52, server: django-deploy.rezayogaswara.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/rezayogaswara/python_projects/django-deploy.sock:", host: "django-deploy.rezayogaswara.com"
2022/05/06 09:36:40 [crit] 477#477: *22 connect() to unix:///home/rezayogaswara/python_projects/django-deploy.sock failed (2: No such file or directory) while connecting to upstream, client: 139.195.129.52, server: django-deploy.rezayogaswara.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/rezayogaswara/python_projects/django-deploy.sock:", host: "django-deploy.rezayogaswara.com"
2022/05/06 09:36:42 [crit] 477#477: *22 connect() to unix:///home/rezayogaswara/python_projects/django-deploy.sock failed (2: No such file or directory) while connecting to upstream, client: 139.195.129.52, server: django-deploy.rezayogaswara.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/rezayogaswara/python_projects/django-deploy.sock:", host: "django-deploy.rezayogaswara.com"
2022/05/06 09:36:43 [crit] 477#477: *22 connect() to unix:///home/rezayogaswara/python_projects/django-deploy.sock failed (2: No such file or directory) while connecting to upstream, client: 139.195.129.52, server: django-deploy.rezayogaswara.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/rezayogaswara/python_projects/django-deploy.sock:", host: "django-deploy.rezayogaswara.com"
2022/05/06 09:37:05 [crit] 477#477: *22 connect() to unix:///home/rezayogaswara/python_projects/django-deploy.sock failed (2: No such file or directory) while connecting to upstream, client: 139.195.129.52, server: django-deploy.rezayogaswara.com, request: "GET / HTTP/1.1", upstream: "uwsgi://unix:///home/rezayogaswara/python_projects/django-deploy.sock:", host: "django-deploy.rezayogaswara.com"
